In [1]:
from scipy.sparse import csr_matrix
import numpy as np

In [2]:
data = np.array([1, 2, 3, 4, 5, 6])
indptr = np.array([0, 6])
indices = np.array([0, 2, 2, 0, 2,1])
b = csr_matrix((data, indices, indptr), shape=(1, 10))

In [3]:
print (b)

  (0, 0)	1
  (0, 2)	2
  (0, 2)	3
  (0, 0)	4
  (0, 2)	5
  (0, 1)	6


In [4]:
b.toarray()

array([[ 5,  6, 10,  0,  0,  0,  0,  0,  0,  0]])

In [5]:
data = np.array(   [1, 2, 3, 4, 5, 6])
indices = np.array([0, 2, 4, 5, 3, 1])
b2 = csr_matrix( ( data,  ( 0*indices, indices)), shape=(1,10)   )


In [6]:
print (b2)

  (0, 0)	1
  (0, 1)	6
  (0, 2)	2
  (0, 3)	5
  (0, 4)	3
  (0, 5)	4


In [7]:
b2.toarray()

array([[1, 6, 2, 5, 3, 4, 0, 0, 0, 0]], dtype=int64)

In [8]:
data = np.array(   [1, 2, 3, 4, 5, 6])
indices = np.array([7, 2, 4, 5, 3, 9])
b2 = csr_matrix( ( data,  ( 0*indices, indices)), shape=(1,10)   )
print (b2)

  (0, 2)	2
  (0, 3)	5
  (0, 4)	3
  (0, 5)	4
  (0, 7)	1
  (0, 9)	6


In [9]:
b2.toarray()

array([[0, 0, 2, 5, 3, 4, 0, 1, 0, 6]], dtype=int64)

In [12]:
for x,y in zip( [ 1,2,3], [4,5,6]):
    print (x)
    print (y)

1
4
2
5
3
6


In [ ]:
i=15
p,v = FD.rdrawframe(i)


In [ ]:
w= np.where( np.in1d( p, pixelist  ) )[0]
b10 = csr_matrix( ( v[w],  ( 0*w, w)), shape=(1, len(pixelist) )   )

In [ ]:
b10.multiply(b15)

In [ ]:
np.bincount(pixelist, weights= np.ravel( bm.toarray() ) )[1:]